### ISSUE TITLE
Update Secret Codes

### ISSUE THREAD

**Issue by SecUpwN** [SimonMarquis/Android-SecretCodes#10]
Good evening @SimonMarquis, I still love your app and thought [this article](http://www.xdalab.com/2016/01/best-2016-secret-code-for-android.html) could be good for an update.

**Comment by SimonMarquis** [comment]
Hi,
I don't really get it...
Do you want me to update my app to list these codes?
If so, I won't be able to do so, simply because the app only lists publicly available codes (by crawling the AndroidManifest of installed apps on the device).

**Comment by SecUpwN** [comment]
>Do you want me to update my app to list these codes?

No, I just thought this article would be useful to improve your app. Thanks anyhow, Issue solved.
