### ISSUE TITLE
Android 7.0

### ISSUE THREAD

**Issue by F0RIS** [SimonMarquis/Android-SecretCodes#17]
App doesnt work on latest official Samsung's ROM
![ghdueqwj1w8](https://cloud.githubusercontent.com/assets/10178982/23212481/91f2844c-f90f-11e6-99fc-0402556bc59b.jpg)

**Comment by SimonMarquis** [comment]
What this code is supposed to do?
Also, send me the corresponding logs when trying to execute this code.

**Comment by F0RIS** [comment]
@SimonMarquis ouch, I made screenshot too early, there is no error message on it) huh. 

I am getting SecurityException with message
`Your device isn\'t compatible…\nTry to execute the code directly from the dialer app.`

It doesnt matter which code I click, it's same for all codes

[Log.txt](https://github.com/SimonMarquis/Android-SecretCodes/files/793592/Log.txt)

**Comment by SimonMarquis** [comment]
The toast comes from [here](https://github.com/SimonMarquis/Android-SecretCodes/blob/125b5bf88507892397d947c712be357922d5fefe/app/src/main/java/fr/simon/marquis/secretcodes/MainActivity.java#L108).
Some OS are preventing sending such Broadcast Intents and the app can't do anything about it.

Did you try to type the exact same code (with # and *) in the default Dialer app on your device?

**Comment by F0RIS** [comment]
Tried, no effect. Even on android 6.0 it's was not work, thats why I used your app. Probably Samsung did something with dialer or I don't know... Their service menu and IMEI checking works fine.

Tried another dialer apps. When I typing last star, apps crashing :(

`java.lang.SecurityException: Permission Denial: not allowed to send broadcast android.provider.Telephony.SECRET_CODE from pid=29659, uid=10267`

<img src="https://cloud.githubusercontent.com/assets/10178982/23215496/408f5dd0-f91b-11e6-8a1c-2332bc0c43a6.jpg" width="200">
<img src="https://cloud.githubusercontent.com/assets/10178982/23215497/40909736-f91b-11e6-9c90-aea25454df0b.jpg" width="200">

**Comment by SimonMarquis** [comment]
Unfortunately, it seems that more and more OS manufacturers are preventing the use of this tool.
And I don't have any solution for this, sorry.

FYI: IMEI popup (*#06 if I remember correctly) and others are slightly different than actual secret codes. And most importantly, they are officially supported by manufacturers (it might also be part of the compatibility test suite required by Google).
