### ISSUE TITLE
Помогите

### ISSUE THREAD

**Issue by vaigar890** [SimonMarquis/Android-SecretCodes#27]
Доброго времени суток. Меня зовут Леонид. Огромное спасибо за внимание которое Вы уделяете.
Мой телефон: Samsung Galaxy A51; SM-A515F/N
  На моём телефоне коды " *#*# - #*#* " не работают, даже если нажать на ввод.
 Помогите пожалуйста.
 С уважением Леонид.

**Comment by NA0341** [comment]
Here's a translation for the above comment:

```
Good day. My name is Leonid. Thank you so much for the attention you pay.
My phone: Samsung Galaxy A51; SM-A515F / N
On my phone, the codes "## - ##" do not work, even if you click on the input.
Help me please.
Sincerely Leonid.
```

@vaigar890 **First of all - please use English here!**
For your specific case it's probably best to search at places like StackOverflow or XDA Developers. This question of yours might be out of scope for this specific application.

Best wishes & luck from Germany.

⪩ 𝓑𝓮𝓵𝓪 ⪨ ~ NA0341 :tulip:
