### ISSUE TITLE
update to newest version on f-droid / add f-droid button to website

### ISSUE THREAD

**Issue by landry314** [SimonMarquis/Android-SecretCodes#7]
1) the version on f-droid is slightly behind the play store. please upload the new source code!

2) please add a "Get it on F-Droid" button next to the Play Store button on your website!

**Comment by SimonMarquis** [comment]
Hi @landry314,

I thought updating the app was an automated process. Can you link me to the right webpage to upload the new version?
Are there any branding material I can use?

**Comment by landry314** [comment]
it says "Auto-update mode: None"

https://f-droid.org/wiki/page/fr.simon.marquis.secretcodes

**Comment by SimonMarquis** [comment]
I wasn't aware of this tool.
What are the steps to enable the auto-update mode?

2015-06-03 18:29 GMT+02:00 Landry <notifications@github.com>:

> it says "Auto-update mode: None"
>
> https://f-droid.org/wiki/page/fr.simon.marquis.secretcodes
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SimonMarquis/Android-SecretCodes/issues/7#issuecomment-108512067>
> .
>



-- 
Simon Marquis
*Email :* contact@simon-marquis.fr
*Site :* www.simon-marquis.fr

**Comment by landry314** [comment]
i have never done this. this will help:

https://f-droid.org/contribute/

**Comment by landry314** [comment]
https://gitlab.com/fdroid/fdroiddata/blob/master/README.md
https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md
